# Generated by Django 4.1 on 2022-08-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='cnn_employer',
            new_name='bloomberg_employer',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='cnn_name',
            new_name='bloomberg_name',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='cnn_note',
            new_name='bloomberg_note',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='cnn_occupation',
            new_name='bloomberg_occupation',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='contribution_total_2018',
        ),
    ]
