# Generated by Django 4.1 on 2022-08-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_rename_cnn_employer_donor_bloomberg_employer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='contribution_total_2022',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
