# Generated by Django 4.2.1 on 2023-06-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_contribution_total_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='contribution_total_2024',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
